# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/HEART/Desktop/禅大师上下架软件监控/CDSGui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 239, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_set_jk = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_set_jk.setChecked(True)
        self.radioButton_set_jk.setObjectName("radioButton_set_jk")
        self.horizontalLayout.addWidget(self.radioButton_set_jk)
        self.radioButton_set_host = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_set_host.setObjectName("radioButton_set_host")
        self.horizontalLayout.addWidget(self.radioButton_set_host)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(580, 0, 239, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_set_ip = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_set_ip.setChecked(True)
        self.radioButton_set_ip.setObjectName("radioButton_set_ip")
        self.horizontalLayout_2.addWidget(self.radioButton_set_ip)
        self.radioButton_set_mail = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioButton_set_mail.setObjectName("radioButton_set_mail")
        self.horizontalLayout_2.addWidget(self.radioButton_set_mail)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 190, 561, 241))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.tableWidget)
        self.frame_IPList = QtWidgets.QFrame(self.centralwidget)
        self.frame_IPList.setGeometry(QtCore.QRect(580, 190, 441, 321))
        self.frame_IPList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_IPList.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_IPList.setObjectName("frame_IPList")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.frame_IPList)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 441, 241))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.listWidget_ip = QtWidgets.QListWidget(self.horizontalLayoutWidget_6)
        self.listWidget_ip.setObjectName("listWidget_ip")
        self.horizontalLayout_6.addWidget(self.listWidget_ip)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.frame_IPList)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(0, 240, 441, 80))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_clearIP = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.pushButton_clearIP.setObjectName("pushButton_clearIP")
        self.horizontalLayout_13.addWidget(self.pushButton_clearIP)
        self.pushButton_deleteIP = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.pushButton_deleteIP.setObjectName("pushButton_deleteIP")
        self.horizontalLayout_13.addWidget(self.pushButton_deleteIP)
        self.frame_SMList = QtWidgets.QFrame(self.centralwidget)
        self.frame_SMList.setGeometry(QtCore.QRect(580, 190, 441, 381))
        self.frame_SMList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SMList.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SMList.setObjectName("frame_SMList")
        self.frame_IPList_2 = QtWidgets.QFrame(self.frame_SMList)
        self.frame_IPList_2.setGeometry(QtCore.QRect(0, 0, 441, 241))
        self.frame_IPList_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_IPList_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_IPList_2.setObjectName("frame_IPList_2")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.frame_IPList_2)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 0, 441, 241))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.listWidget_mail = QtWidgets.QListWidget(self.horizontalLayoutWidget_8)
        self.listWidget_mail.setObjectName("listWidget_mail")
        self.horizontalLayout_8.addWidget(self.listWidget_mail)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.frame_SMList)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(0, 240, 441, 51))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_clearMail = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_clearMail.setObjectName("pushButton_clearMail")
        self.horizontalLayout_11.addWidget(self.pushButton_clearMail)
        self.pushButton_delteMail = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_delteMail.setObjectName("pushButton_delteMail")
        self.horizontalLayout_11.addWidget(self.pushButton_delteMail)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.frame_SMList)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 270, 441, 80))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_sendMail = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_sendMail.setObjectName("pushButton_sendMail")
        self.horizontalLayout_7.addWidget(self.pushButton_sendMail)
        self.pushButton_saveMail = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_saveMail.setObjectName("pushButton_saveMail")
        self.horizontalLayout_7.addWidget(self.pushButton_saveMail)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(580, 160, 239, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_list_ip = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_list_ip.setChecked(True)
        self.radioButton_list_ip.setObjectName("radioButton_list_ip")
        self.horizontalLayout_4.addWidget(self.radioButton_list_ip)
        self.radioButton_list_mail = QtWidgets.QRadioButton(self.horizontalLayoutWidget_4)
        self.radioButton_list_mail.setObjectName("radioButton_list_mail")
        self.horizontalLayout_4.addWidget(self.radioButton_list_mail)
        self.frame_JK = QtWidgets.QFrame(self.centralwidget)
        self.frame_JK.setGeometry(QtCore.QRect(10, 30, 351, 151))
        self.frame_JK.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_JK.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_JK.setObjectName("frame_JK")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_JK)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 261, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.radioButton_up = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_up.setChecked(True)
        self.radioButton_up.setObjectName("radioButton_up")
        self.gridLayout.addWidget(self.radioButton_up, 1, 0, 1, 1)
        self.spinBox_day = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_day.setObjectName("spinBox_day")
        self.gridLayout.addWidget(self.spinBox_day, 0, 1, 1, 1)
        self.radioButton_down = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_down.setObjectName("radioButton_down")
        self.gridLayout.addWidget(self.radioButton_down, 1, 1, 1, 1)
        self.comboBox_type = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_type.setObjectName("comboBox_type")
        self.gridLayout.addWidget(self.comboBox_type, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.radioButton_keys = QtWidgets.QRadioButton(self.frame_JK)
        self.radioButton_keys.setGeometry(QtCore.QRect(0, 130, 72, 19))
        self.radioButton_keys.setChecked(True)
        self.radioButton_keys.setObjectName("radioButton_keys")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_JK)
        self.lineEdit.setGeometry(QtCore.QRect(130, 130, 221, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.frame_SMF = QtWidgets.QFrame(self.centralwidget)
        self.frame_SMF.setGeometry(QtCore.QRect(10, 60, 291, 61))
        self.frame_SMF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SMF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SMF.setObjectName("frame_SMF")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame_SMF)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 291, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_host = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.horizontalLayout_5.addWidget(self.lineEdit_host)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.frame_SMF)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 30, 291, 31))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.lineEdit_pass = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.horizontalLayout_10.addWidget(self.lineEdit_pass)
        self.frame_IPadd = QtWidgets.QFrame(self.centralwidget)
        self.frame_IPadd.setGeometry(QtCore.QRect(580, 30, 401, 81))
        self.frame_IPadd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_IPadd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_IPadd.setObjectName("frame_IPadd")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_IPadd)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 401, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_ipadd = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_ipadd.setObjectName("lineEdit_ipadd")
        self.gridLayout_2.addWidget(self.lineEdit_ipadd, 0, 1, 1, 1)
        self.pushButton_ipadd = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_ipadd.setObjectName("pushButton_ipadd")
        self.gridLayout_2.addWidget(self.pushButton_ipadd, 0, 2, 1, 1)
        self.pushButton_ipLoad = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_ipLoad.setObjectName("pushButton_ipLoad")
        self.gridLayout_2.addWidget(self.pushButton_ipLoad, 1, 0, 1, 3)
        self.frame_SMadd = QtWidgets.QFrame(self.centralwidget)
        self.frame_SMadd.setGeometry(QtCore.QRect(580, 30, 401, 81))
        self.frame_SMadd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SMadd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SMadd.setObjectName("frame_SMadd")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.frame_SMadd)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 401, 80))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_mailadd = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_mailadd.setObjectName("lineEdit_mailadd")
        self.gridLayout_5.addWidget(self.lineEdit_mailadd, 0, 1, 1, 1)
        self.pushButton_mailadd = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_mailadd.setObjectName("pushButton_mailadd")
        self.gridLayout_5.addWidget(self.pushButton_mailadd, 0, 2, 1, 1)
        self.pushButton_mailLoad = QtWidgets.QPushButton(self.gridLayoutWidget_5)
        self.pushButton_mailLoad.setObjectName("pushButton_mailLoad")
        self.gridLayout_5.addWidget(self.pushButton_mailLoad, 1, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(560, 0, 20, 521))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(400, 40, 121, 111))
        self.startButton.setObjectName("startButton")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(0, 430, 541, 80))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_saveInfo = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.pushButton_saveInfo.setObjectName("pushButton_saveInfo")
        self.horizontalLayout_12.addWidget(self.pushButton_saveInfo)
        self.pushButton_clearInfo = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.pushButton_clearInfo.setObjectName("pushButton_clearInfo")
        self.horizontalLayout_12.addWidget(self.pushButton_clearInfo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.radioButton_set_jk.toggled['bool'].connect(self.frame_JK.setVisible)
        self.radioButton_set_host.toggled['bool'].connect(self.frame_SMF.setVisible)
        self.radioButton_list_ip.toggled['bool'].connect(self.frame_IPList.setVisible)
        self.radioButton_list_mail.toggled['bool'].connect(self.frame_SMList.setVisible)
        self.radioButton_set_ip.toggled['bool'].connect(self.frame_IPadd.setVisible)
        self.radioButton_set_mail.toggled['bool'].connect(self.frame_SMadd.setVisible)
        self.radioButton_keys.toggled['bool'].connect(self.lineEdit.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_set_jk.setText(_translate("MainWindow", "软件监控"))
        self.radioButton_set_host.setText(_translate("MainWindow", "发件邮箱"))
        self.radioButton_set_ip.setText(_translate("MainWindow", "代理IP设置"))
        self.radioButton_set_mail.setText(_translate("MainWindow", "收件邮箱设置"))
        self.pushButton_clearIP.setText(_translate("MainWindow", "清空"))
        self.pushButton_deleteIP.setText(_translate("MainWindow", "删除"))
        self.pushButton_clearMail.setText(_translate("MainWindow", "清空"))
        self.pushButton_delteMail.setText(_translate("MainWindow", "删除"))
        self.pushButton_sendMail.setText(_translate("MainWindow", "发送邮件"))
        self.pushButton_saveMail.setText(_translate("MainWindow", "导出信息"))
        self.radioButton_list_ip.setText(_translate("MainWindow", "代理IP表"))
        self.radioButton_list_mail.setText(_translate("MainWindow", "收件邮箱表"))
        self.label.setText(_translate("MainWindow", "监控天数"))
        self.radioButton_up.setText(_translate("MainWindow", "上架软件"))
        self.radioButton_down.setText(_translate("MainWindow", "下架软件"))
        self.label_2.setText(_translate("MainWindow", "软件类别"))
        self.radioButton_keys.setText(_translate("MainWindow", "关键字"))
        self.label_3.setText(_translate("MainWindow", "邮箱号"))
        self.label_5.setText(_translate("MainWindow", "授权码"))
        self.label_6.setText(_translate("MainWindow", "代理IP"))
        self.pushButton_ipadd.setText(_translate("MainWindow", "添加"))
        self.pushButton_ipLoad.setText(_translate("MainWindow", "导入txt文件"))
        self.label_9.setText(_translate("MainWindow", "邮箱号"))
        self.pushButton_mailadd.setText(_translate("MainWindow", "添加"))
        self.pushButton_mailLoad.setText(_translate("MainWindow", "导入txt文件"))
        self.startButton.setText(_translate("MainWindow", "开始监控"))
        self.pushButton_saveInfo.setText(_translate("MainWindow", "保存信息"))
        self.pushButton_clearInfo.setText(_translate("MainWindow", "清空列表"))

